#!/bin/sh

# set root pointer
xsetroot -cursor_name left_ptr &

#picom 
pkill picom
picom -b &
#picom --expiremental-backends --no-use-damage &
feh --bg-scale "$HOME/Pictures/wallpapers/Decay-Green/moments_before_desk.png"
# key bindings
sxhkd -c "$HOME/.config/bspwm/sxhkdrc" &
blueman-applet &
nm-applet &
dunst &

var=$(xinput --list | grep 'MSFT0001:01 04F3:309E Touchpad' | awk '{print $6}' | awk -F '=' '{print $2}')
xinput --set-prop $var 'libinput Natural Scrolling Enabled' 1
xinput --set-prop $var 'libinput Tapping Enabled' 1
setxkbmap -option caps:escape

# panel
#tint2 &
# $HOME/.config/polybar/launch.sh &

# set some bsp specific
bspc monitor -d 1 2 3 4 5 6

bspc config window_gap 12
bspc config border_width 2

bspc config split_ratio 0.5
bspc config borderless_monocle false
bspc config gapless_monocle false

# bspc rule -a '*' state=floating follow=on

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc rule -a firefox desktop=^1 state=tiled follow=on
bspc rule -a Alacritty desktop=^3 state=tiled follow=on
bspc rule -a kitty desktop=^2 state=tiled follow=on
bspc rule -a discord desktop=^5 state=fullscreen follow=on
# bspc rule -a discord-screenaudio desktop=yay state=fullscreen follow=on
bspc rule -a Blender desktop=^5 state=fullscreen follow=on
bspc rule -a Slack desktop=^5 state=fullscreen follow=on
bspc rule -a editor desktop=^2 state=tiled follow=on
bspc rule -a Godot desktop=^5 state=fullscreen follow=on
bspc rule -a Wireshark desktop=^4 state=fullscreen follow=on
polybar-msg cmd hide
