#!/bin/bash
CONFIG="-Lterm -f $HOME/.config/tmux/tmux.conf"
if [[ -z $(pgrep tmux) ]]; then
	tmux $CONFIG term new-session -s term
else
	INFO=$(tmux $CONFIG list-session -F "#{session_name}:#{session_attached}")
	IS_ATTACHED=$(echo "$INFO" | awk -F ':' '{ if ( $1 == "term" ) print $2 }')
	if [[ "$IS_ATTACHED" == "1" ]]; then
		tmux $CONFIG neww -t term
	else
		tmux $CONFIG new-session -A -s term
	fi
fi
